//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sport.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int id { get; set; }
        public int role { get; set; }
        public string firstname { get; set; }
        public string username { get; set; }
        public string patronym { get; set; }
        public string email { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string phone { get; set; }
        public int seria { get; set; }
        public int number { get; set; }
        public System.DateTime birthday { get; set; }
        public Nullable<System.DateTime> lastpass { get; set; }
        public Nullable<int> status { get; set; }
        public int gender { get; set; }
    
        public virtual gender gender1 { get; set; }
        public virtual role role1 { get; set; }
        public virtual status status1 { get; set; }
    }
}
